name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "* * * * *"}]
  #schedule: [{cron: "0 */24 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: Minghao2812
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          ## plugin: most used languages
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          ## plugin: coding habits
          plugin_habits: yes

          filename: metrics.classic.svg
          plugin_lines: yes
